language: node_js

node_js: '14.8.0'

cache:
  directories:
    - node_modules #缓存依赖
    - server/node_modules
    - client/node_modules

# S: Build Lifecycle
install:
  - npm i

script:
  - npm run build


before_script
 - cd ..
 - git clone https://github.com/antvis/G2Plot.git
 - cd ./release-inspection-of-antv
