language: node_js

node_js: '14.8.0'

cache:
  directories:
    - node_modules #缓存依赖
    - server/node_modules
    - client/node_modules

# S: Build Lifecycle
install:
  - npm i

script:
  - npm run build

before_script:
  - cd ..
  - git clone https://github.com/antvis/G2Plot.git
  - cd ./release-inspection-of-antv

after_script:
  - pwd
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git config core.filemode false
  - gi config --list
  - git checkout -b ${D_BRANCH}
  - git add .
  - git commit -m "Deploy by Travis CI"
  - git push --set-upstream origin ${D_BRANCH} -f

branches:
  only:
    - master
